### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by swedishmike** [corelight/conn-burst#1]
I tried to install this and it fails on every machine I try it on.

I've followed the instructions and run

bro-pkg refresh
bro-pkg install bro/corelight/conn-burst

This generates the following error message:

```
root@xxxx:/usr/local/bro/logs# bro-pkg install bro/corelight/conn-burst
error: invalid package "bro/corelight/conn-burst": package name not found in sources and not a valid git URL
```

I had a look in the https://github.com/bro/packages/blob/master/corelight/bro-pkg.index file and the conn-burst package isn't mentioned there. Could this be the issue?

Cheers, Mike

**Comment by sethhall** [comment]
Sorry about that.  I hadn't added it to the global package manager repository yet, but I just got it in there now.  Definitely let me know if any results from this script don't seem right!  Thanks.
